### ISSUE TITLE
Blank space appearing at the bottom of the page when only one or two portfolios are displayed

### ISSUE THREAD

**Issue by joelgnansounou** [JacobGomez325/benin-portfolio-v2#13]
**Description:**
When the list of portfolios is filtered to show only one or two results, a blank space appears at the bottom of the page.

**Expected behavior:**
The page should adjust dynamically to the number of portfolios displayed, without any blank space at the bottom.

**Screenshots:**
<img width="1512" alt="benin-portfolio-issue" src="https://github.com/JacobGomez325/benin-portfolio-v2/assets/39857865/ac798a85-7ee0-4782-b8fe-a97aa90248bd">

**Possible solution:**
Adjust the CSS or layout of the portfolios list section to prevent the blank space from appearing when only one or two portfolios are displayed.

**Comment by JacobGomez325** [comment]
okey i understand thanks
