### ISSUE TITLE
Synchronisation de la recherche et du filtre pour une expérience utilisateur améliorée

### ISSUE THREAD

**Issue by JacobGomez325** [JacobGomez325/benin-portfolio-v2#3]
## Synchronisation de la recherche et du filtre pour une expérience utilisateur améliorée
Actuellement, notre application propose deux fonctionnalités distinctes : la recherche et le filtre, qui sont indépendantes l'une de l'autre. Cependant, pour offrir une expérience utilisateur plus fluide et intuitive, nous souhaitons synchroniser ces deux aspects afin que la recherche puisse être effectuée en fonction des éléments sélectionnés dans le filtre.

### Voici comment nous envisageons cette synchronisation :

**Recherche globale** : Lorsque le filtre n'est pas activé, la recherche reste globale, permettant à l'utilisateur de rechercher des éléments dans l'ensemble de l'application sans restriction.
**Recherche filtrée** : Si le filtre est activé, la recherche doit être restreinte aux critères définis par les éléments sélectionnés dans le filtre. Cela signifie que seuls les éléments correspondant aux paramètres du filtre seront inclus dans les résultats de recherche.

**Comment by ludndev** [comment]
Fixed on  #11  by @lauryne1.

**Comment by ludndev** [comment]
Can you closed this issue @JacobGomez325 ?

**Comment by JacobGomez325** [comment]
yes thanks bro
